import {
  UserProfile,
  Attachment,
  LogbookEntry,
  HostCompany,
  SupervisoryVisit,
  CompetencyUnit,
} from '@/types';

export const INITIAL_PROFILES: Record<string, UserProfile> = {
  TRAINEE: {
    id: 'user-trainee-1',
    name: 'Faith Cherono',
    email: 'faith.cherono@student.npt.ac.ke',
    role: 'TRAINEE',
    avatar: 'https://picsum.photos/seed/skilltrack-trainee/400/400',
    institution: 'Nairobi Technical Polytechnic',
    department: 'Electrical & Electronics Engineering',
    designation: 'Level 6 Diploma Attachee',
  },
  MENTOR: {
    id: 'user-mentor-1',
    name: 'Martin Ouma',
    email: 'm.ouma@apexmechatronics.co.ke',
    role: 'MENTOR',
    avatar: 'https://picsum.photos/seed/skilltrack-mentor/400/400',
    organization: 'Apex Mechatronics Ltd',
    designation: 'Senior Automation Engineer & Certified TVET Mentor',
  },
  ILO: {
    id: 'user-ilo-1',
    name: 'Grace Mbandi',
    email: 'g.mbandi@npt.ac.ke',
    role: 'ILO',
    avatar: 'https://picsum.photos/seed/skilltrack-ilo/400/400',
    institution: 'Nairobi Technical Polytechnic',
    designation: 'Head of Industry Liaison & Placement Office',
  },
  INSTITUTION_ADMIN: {
    id: 'user-admin-1',
    name: 'Prof. David Koech',
    email: 'd.koech@npt.ac.ke',
    role: 'INSTITUTION_ADMIN',
    avatar: '',
    institution: 'Nairobi Technical Polytechnic',
    designation: 'Dean, School of Engineering & Applied Trades',
  },
  SUPER_ADMIN: {
    id: 'user-super-1',
    name: 'Dr. Joyce Mutua',
    email: 'j.mutua@tvetauthority.go.ke',
    role: 'SUPER_ADMIN',
    avatar: '',
    organization: 'National TVET Quality Assurance Directorate',
    designation: 'Director of Workplace Apprenticeships & Standards',
  },
};

export const INITIAL_ATTACHMENTS: Attachment[] = [
  {
    id: 'att-001',
    traineeId: 'user-trainee-1',
    traineeName: 'Faith Cherono',
    traineeRegNumber: 'NPT/EEE/2024/0482',
    traineeAvatar: 'https://picsum.photos/seed/skilltrack-trainee/400/400',
    trade: 'Electrical & Electronics Engineering (Industrial Automation)',
    level: 'TVET Level 6',
    institutionName: 'Nairobi Technical Polytechnic',
    hostCompanyId: 'comp-apex',
    hostCompanyName: 'Apex Mechatronics Ltd',
    hostLocation: 'Industrial Area, Commercial Street Block 4',
    mentorId: 'user-mentor-1',
    mentorName: 'Martin Ouma',
    mentorRole: 'Senior Automation Engineer',
    mentorAvatar: 'https://picsum.photos/seed/skilltrack-mentor/400/400',
    startDate: '2026-08-15',
    endDate: '2026-11-15',
    totalWeeks: 12,
    completedWeeks: 8,
    loggedHours: 320,
    requiredHours: 480,
    competencyScore: 82,
    status: 'ACTIVE',
  },
  {
    id: 'att-002',
    traineeId: 'user-trainee-2',
    traineeName: 'Kevin Mwangi',
    traineeRegNumber: 'NPT/ME/2024/0119',
    traineeAvatar: '',
    trade: 'Mechanical Production (CNC & Precision Machining)',
    level: 'TVET Level 6',
    institutionName: 'Nairobi Technical Polytechnic',
    hostCompanyId: 'comp-metal',
    hostCompanyName: 'Standard Metalworks & Fabrication',
    hostLocation: 'Athi River Heavy Industrial Zone',
    mentorId: 'user-mentor-2',
    mentorName: 'Benson Kimani',
    mentorRole: 'Toolroom Superintendent',
    mentorAvatar: '',
    startDate: '2026-08-15',
    endDate: '2026-11-15',
    totalWeeks: 12,
    completedWeeks: 7,
    loggedHours: 280,
    requiredHours: 480,
    competencyScore: 78,
    status: 'ACTIVE',
  },
  {
    id: 'att-003',
    traineeId: 'user-trainee-3',
    traineeName: 'Amina Hassan',
    traineeRegNumber: 'NPT/AUT/2024/0304',
    traineeAvatar: '',
    trade: 'Automotive Mechatronics & Hybrid Diagnostics',
    level: 'TVET Level 5',
    institutionName: 'Nairobi Technical Polytechnic',
    hostCompanyId: 'comp-kipevu',
    hostCompanyName: 'Kipevu Thermal Energy Corp',
    hostLocation: 'Mombasa Port Maintenance Yard',
    mentorId: 'user-mentor-3',
    mentorName: 'Hassan Juma',
    mentorRole: 'Fleet Maintenance Manager',
    mentorAvatar: '',
    startDate: '2026-08-15',
    endDate: '2026-11-15',
    totalWeeks: 12,
    completedWeeks: 8,
    loggedHours: 312,
    requiredHours: 480,
    competencyScore: 89,
    status: 'ACTIVE',
  },
  {
    id: 'att-004',
    traineeId: 'user-trainee-4',
    traineeName: 'Brian Otieno',
    traineeRegNumber: 'NPT/SOL/2024/0521',
    traineeAvatar: '',
    trade: 'Solar Photovoltaic Installation & Microgrids',
    level: 'TVET Level 5',
    institutionName: 'Nairobi Technical Polytechnic',
    hostCompanyId: 'comp-rift',
    hostCompanyName: 'Rift Valley Solar Solutions',
    hostLocation: 'Nakuru Green Energy Hub',
    mentorId: 'user-mentor-4',
    mentorName: 'Alice Sang',
    mentorRole: 'Lead Commissioning Engineer',
    mentorAvatar: '',
    startDate: '2026-08-15',
    endDate: '2026-11-15',
    totalWeeks: 12,
    completedWeeks: 8,
    loggedHours: 320,
    requiredHours: 480,
    competencyScore: 75,
    status: 'ACTIVE',
  },
];

export const INITIAL_LOGBOOKS: LogbookEntry[] = [
  {
    id: 'log-001',
    attachmentId: 'att-001',
    weekNumber: 8,
    dayOfWeek: 'Thursday',
    date: '2026-10-08',
    hours: 8,
    title: 'PLC Control Panel Troubleshooting & Three-Phase Contactor Wiring',
    description:
      'Diagnosed intermittent tripping on Packaging Line 2 conveyer drive. Followed lockout/tagout procedure. Traced 24V DC sensor loops using a Fluke multimeter. Identified faulty inductive proximity sensor and oxidized contactor terminal block. Replaced contactor, re-crimped lugs with heat shrink, and verified PLC input status led on Siemens S7-1200 rack.',
    trade: 'Electrical & Electronics Engineering',
    toolsEquipment: 'Siemens S7-1200 PLC, Fluke 87V Digital Multimeter, Insulated Screwdrivers, Wire Stripper, LOTO Padlock',
    competencyTags: [
      'OSHA Lockout/Tagout Safety',
      'Control Circuit Schematic Tracing',
      'PLC Digital I/O Diagnostics',
      'Industrial Electrical Termination',
    ],
    safetyCompliance: true,
    ppeConfirmed: true,
    status: 'SUBMITTED', // Pending mentor review!
    aiFeedback:
      'High technical clarity. Clearly documented isolation protocols and diagnostic steps adhering to KNQA Level 6 Occupational Standard EE/OS/004.',
  },
  {
    id: 'log-002',
    attachmentId: 'att-001',
    weekNumber: 8,
    dayOfWeek: 'Wednesday',
    date: '2026-10-07',
    hours: 8,
    title: 'Variable Frequency Drive (VFD) Parameter Configuration',
    description:
      'Configured ramp-up and ramp-down acceleration times on Danfoss VLT AutomationDrive for mixer motor. Calculated full-load current (14.2A) and set motor overload thermal protection parameters according to motor nameplate specifications. Ran loaded test cycle.',
    trade: 'Electrical & Electronics Engineering',
    toolsEquipment: 'Danfoss VLT Drive, Digital Tachometer, Clamp-on Ammeter',
    competencyTags: ['Electric Motor Drives', 'Motor Thermal Protection', 'Parameter Commissioning'],
    safetyCompliance: true,
    ppeConfirmed: true,
    status: 'APPROVED',
    mentorRating: 5,
    mentorFeedback:
      'Excellent precision in verifying motor nameplate parameters against drive registers. Thorough safety awareness during live testing.',
    reviewedAt: '2026-10-07 17:30',
    reviewedBy: 'Martin Ouma',
  },
  {
    id: 'log-003',
    attachmentId: 'att-001',
    weekNumber: 8,
    dayOfWeek: 'Tuesday',
    date: '2026-10-06',
    hours: 8,
    title: 'Pneumatic Actuator Solenoid Valve Replacement',
    description:
      'Depressurized pneumatic header to 0 bar. Removed leaking 5/2 directional control solenoid valve from manifold. Replaced polyurethane push-in fittings, sealed threads with PTFE tape, re-pressurized to 6 bar, and executed leak test with soapy water solution.',
    trade: 'Electrical & Electronics Engineering',
    toolsEquipment: 'Pneumatic Test Bench, Open-end Wrenches, PTFE Tape, Pressure Gauge',
    competencyTags: ['Pneumatic System Maintenance', 'Piping & Fittings Assembly', 'Pressure Safety Protocol'],
    safetyCompliance: true,
    ppeConfirmed: true,
    status: 'APPROVED',
    mentorRating: 4,
    mentorFeedback: 'Good methodical leak check. Remember to write down the torque spec on valve manifold screws.',
    reviewedAt: '2026-10-06 18:15',
    reviewedBy: 'Martin Ouma',
  },
  {
    id: 'log-004',
    attachmentId: 'att-001',
    weekNumber: 7,
    dayOfWeek: 'Friday',
    date: '2026-10-02',
    hours: 8,
    title: 'Weekly Substation Preventative Inspection & Earth Resistance Test',
    description:
      'Accompanied senior high-voltage technician to inspect 11kV/415V step-down transformer yard. Checked silica gel breather color (deep blue, active), recorded oil level and winding temperatures. Conducted earth loop resistance measurement using Megger earth tester (0.85 ohms measured, within statutory < 1.0 ohm threshold).',
    trade: 'Electrical & Electronics Engineering',
    toolsEquipment: 'Megger 4-Terminal Earth Tester, Infrared Thermal Gun, Class 0 Arc Flash Visor',
    competencyTags: ['High Voltage Substation Inspection', 'Earthing & Grounding Verification', 'Thermal Radiometry'],
    safetyCompliance: true,
    ppeConfirmed: true,
    status: 'APPROVED',
    mentorRating: 5,
    mentorFeedback: 'Commendable vigilance. Faith correctly highlighted the importance of earth impedance in TVET compliance audits.',
    reviewedAt: '2026-10-02 16:45',
    reviewedBy: 'Martin Ouma',
  },
  {
    id: 'log-005',
    attachmentId: 'att-002',
    weekNumber: 7,
    dayOfWeek: 'Thursday',
    date: '2026-10-01',
    hours: 8,
    title: 'CNC Mill Coordinate Setup and G-Code Verification',
    description:
      'Loaded carbide end-mill in Haas CNC machine spindle. Clocked workpiece datum with dial indicator. Verified workpiece coordinates G54 and simulated G-code toolpath to prevent crash.',
    trade: 'Mechanical Production',
    toolsEquipment: 'Haas 3-Axis CNC Machining Center, Dial Test Indicator, Vernier Calipers',
    competencyTags: ['CNC Setup & Zeroing', 'G-Code Simulation', 'Dimensional Metrology'],
    safetyCompliance: true,
    ppeConfirmed: true,
    status: 'APPROVED',
    mentorRating: 4,
    mentorFeedback: 'Setup was clean. Tool offsets were verified with toolmaker microscope.',
    reviewedAt: '2026-10-01 17:00',
    reviewedBy: 'Benson Kimani',
  },
];

export const INITIAL_COMPETENCIES: CompetencyUnit[] = [
  {
    code: 'EE/OS/001',
    title: 'Workplace Health, Safety & Environmental Compliance (OSHA)',
    trade: 'Electrical & Electronics Engineering',
    level: 6,
    masteryPercent: 95,
    verifiedByMentor: true,
    description: 'Adherence to isolation protocols, PPE, emergency stop circuits, and electrical fire hazard protocols.',
  },
  {
    code: 'EE/OS/002',
    title: 'Industrial Electrical Schematics & Circuit Tracing',
    trade: 'Electrical & Electronics Engineering',
    level: 6,
    masteryPercent: 88,
    verifiedByMentor: true,
    description: 'Reading IEC standard single-line and control wiring diagrams, terminal allocation schedules.',
  },
  {
    code: 'EE/OS/003',
    title: 'Programmable Logic Controllers (PLC) & Industrial I/O',
    trade: 'Electrical & Electronics Engineering',
    level: 6,
    masteryPercent: 78,
    verifiedByMentor: false,
    description: 'Ladder logic diagnosis, digital/analog signal troubleshooting, sensor calibration.',
  },
  {
    code: 'EE/OS/004',
    title: 'Electric Motor Drives & Inverter Commissioning',
    trade: 'Electrical & Electronics Engineering',
    level: 6,
    masteryPercent: 82,
    verifiedByMentor: true,
    description: 'Star-Delta and VFD parameter configuration, torque curves, and thermal overload protection.',
  },
  {
    code: 'EE/OS/005',
    title: 'Substation Earthing & Preventative Maintenance',
    trade: 'Electrical & Electronics Engineering',
    level: 6,
    masteryPercent: 70,
    verifiedByMentor: false,
    description: 'Transformer inspections, Megger earth electrode resistance testing, thermal imaging.',
  },
];

export const INITIAL_HOST_COMPANIES: HostCompany[] = [
  {
    id: 'comp-apex',
    name: 'Apex Mechatronics Ltd',
    industry: 'Industrial Automation & Process Controls',
    location: 'Nairobi Industrial Area',
    activeTrainees: 4,
    maxCapacity: 6,
    mouStatus: 'ACTIVE',
    leadMentor: 'Martin Ouma',
    contactEmail: 'attachments@apexmechatronics.co.ke',
  },
  {
    id: 'comp-metal',
    name: 'Standard Metalworks & Fabrication',
    industry: 'Heavy Structural Steel & CNC Machining',
    location: 'Athi River EPZ',
    activeTrainees: 3,
    maxCapacity: 5,
    mouStatus: 'ACTIVE',
    leadMentor: 'Benson Kimani',
    contactEmail: 'liaison@standardmetal.co.ke',
  },
  {
    id: 'comp-kipevu',
    name: 'Kipevu Thermal Energy Corp',
    industry: 'Power Generation & Auxiliary Systems',
    location: 'Mombasa Port Maintenance Yard',
    activeTrainees: 5,
    maxCapacity: 8,
    mouStatus: 'ACTIVE',
    leadMentor: 'Hassan Juma',
    contactEmail: 'tvet@kipevuenergy.com',
  },
  {
    id: 'comp-rift',
    name: 'Rift Valley Solar Solutions',
    industry: 'Commercial Microgrids & Clean Energy',
    location: 'Nakuru Green Tech Corridor',
    activeTrainees: 2,
    maxCapacity: 4,
    mouStatus: 'ACTIVE',
    leadMentor: 'Alice Sang',
    contactEmail: 'internships@riftsolar.co.ke',
  },
];

export const INITIAL_VISITS: SupervisoryVisit[] = [
  {
    id: 'vis-001',
    attachmentId: 'att-001',
    traineeName: 'Faith Cherono',
    companyName: 'Apex Mechatronics Ltd',
    iloName: 'Grace Mbandi',
    visitDate: '2026-10-14',
    status: 'SCHEDULED',
    workplaceFindings: 'Upcoming mid-term monitoring visit to review PLC diagnostic logbooks with Mentor Martin Ouma.',
    safetyScore: 95,
  },
  {
    id: 'vis-002',
    attachmentId: 'att-002',
    traineeName: 'Kevin Mwangi',
    companyName: 'Standard Metalworks & Fabrication',
    iloName: 'Grace Mbandi',
    visitDate: '2026-09-28',
    status: 'COMPLETED',
    workplaceFindings: 'Toolroom facilities compliant. Trainee demonstrating good CNC setup competencies under Benson Kimani.',
    safetyScore: 92,
  },
];
